<template>
  <div style="padding:100px">
    <g-cascader
      popover-height="200px"
      :source="source"
      :selected="selected"
      @update:selected="selected=$event"
    ></g-cascader>
  </div>
</template>
<script>
import Cascader from '../packages/cascader'
export default {
    data(){
        return {
            selected:[],
            source:[{
            name:'浙江',
            children:[
                {
                    name:'嘉兴市',
                    children:[
                        {name:'name1'},
                        {name:'name12'},
                        {name:'name134'}
                    ]
                },
                {
                    name:'湖州市',
                    children:[
                        {name:'name16'},
                        {name:'name126'},
                        {name:'name1346'}
                    ]
                },
                {
                    name:'杭州市',
                    children:[
                        {name:'name167'},
                        {name:'name1267'},
                        {name:'name13467'}
                    ]
                }
            ]
        },{
            name:'浙江2',
            children:[
                {
                    name:'嘉兴市2',
                    children:[
                        {name:'name168'},
                        {name:'name1268'},
                        {name:'name13468'}
                    ]
                },
                {
                    name:'嘉兴市21',
                    children:[
                        {name:'name1681'},
                        {name:'name12681'},
                        {name:'name134681'}
                    ]
                }
            ]
        },{
            name:'浙江2',
            children:[
                {
                    name:'嘉兴市2',
                    children:[
                        {name:'name168'},
                        {name:'name1268'},
                        {name:'name13468'}
                    ]
                },
                {
                    name:'嘉兴市23',
                    children:[
                        {name:'name1683'},
                        {name:'name12683'},
                        {name:'name134683'}
                    ]
                }
            ]
        }]
    }},
    components:{
        gCascader:Cascader
    }
}
</script>
<style lang="scss" scoped>
</style>
